@startuml агро_V1
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
title "Context Diagram"
'title "Платформа управления животноводческим комплексом"
Person(сотрудник, "дежурный сотрудник")

System_Boundary(платформа, "Агротех  - платформа управления животноводческим комплексом") {
    ''Нефункциональные требования
    ''обеспечивать достаточно высокую отказоустойчивость 99,95%;
    ''быть расширяемой, то есть иметь возможность разработать новый функционал без изменений существующего;
    ''иметь высокую производительность — от момента возникновения нештатной ситуации, зафиксированной с помощью видеоаналитики, должно проходить не более 5 секунд до момента оповещения;
    ''позволять системе видеоаналитики реагировать в реальном времени (миллисекунды).    
    
    System(databus, "система передачи и обработки данных", "сбор данных от технических систем, структурирование, хранение ")
    
    System(цуп, "система мониторинга хозяйства", "управление,  мониторинг, анализ, оповещение, отчетность")
    '{
        'работать даже в случае отсутствия интернета и при необходимости отправлиять уведомления дежурному сотруднику на местах мониторинга, а после восстановления связи синхронизироваться с центральной системой;
        'иметь разделение ролей и поддерживать современные способы аутентификации и авторизации;
        'иметь API для создания мобильного приложения или веб-приложения.
        'предоставлять базовые метрики для передачи в другие системы;
        'поддерживать возможность добавления собственных метрик;

    '}
    System(животноводство,"система жизнеобеспечения животных", "Мониторинг состояния технических средств(кормушки, поилки и др)")
    '{
        'управлять кормушками и поилками разных производителей;
        'следить за состоянием систем фильтрации воды;

    '}   
    System(видео,"система видеонаблюдения за животными", "") 
    '{
        'поддерживать необходимое количество видеокамер для аналитики в реальном времени от разных производителей;
    '}       
    
    System(agent, "агент", "система синхронизации с ЦОД Агротех")
    '{
        'быть построена по принципу «центральный сервер — агенты» на конкретных фермах без ограничения количества таких агентов (в синхронизации между агентами и центральным сервером допускается задержка до 10 минут без учёта проблем со связью);
    '} 
    System(collector, "Система сбора данных от хозяйств")
}
    System_Ext(ai, "ИИ-система мониторинга животных", "анализ видео") 
    'Готовую нейросетевую модель предоставят партнёры.
    '{ 
        'фиксировать признаки беспокойного поведения или драк среди животных и оповещать оператора;
        'фиксировать признаки задавливания поросят;
        'оценивать состояние животных по внешнему виду и поведению: болезнь, гибель, беспокойство и так далее;
        'пересчитывать поголовье;
        'делать пересчёт животных;
    '}
    



Rel(видео, ai, "Отправляет", "", "real-time данные с камер наблюдения") 
Rel(ai, databus, "Публикует", "", "структурированные данные о событиях")
Rel(сотрудник, цуп, "Использует", "веб-приложение или мобильное приложение", "для мониторинга и получения оповещений")
Rel(databus, цуп, "Предоставляет", "", "данные о состоянии систем, метрики") 
Rel(животноводство, databus, "Публикует", "", "структурированные данные о состоянии технических систем") 
Rel(agent, цуп, "Запрашивает","","данные о состоянии систем, о событиях и т.д.")
Rel(agent, collector, "Отправляет","","данные о состоянии систем, о событиях и т.д.")


     


@enduml